language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
    - TEST_RUNNER_URI=/run-test.cfm
  matrix:
    - CFENGINE=lucee@5
    - CFENGINE=adobe@11
    - CFENGINE=adobe@2016
before_install:
- git clone --depth 1 https://github.com/foundeo/cfmatrix.git cfmatrix
install:
- cfmatrix/bin/box recipe recipeFile=cfmatrix/ci.boxr CFENGINE=$CFENGINE
before_script:
- chmod +x cfmatrix/run.sh
script:
- "./cfmatrix/run.sh"
